---
- name: Execute bash script and set up cron job
  hosts: your_slave_node
  become: true

  tasks:
    - name: Transfer bash script to slave node
      copy:
        src: /path/to/your/bash/script.sh
        dest: /tmp/script.sh
        mode: 0755

    - name: Execute the bash script
      shell: /tmp/script.sh
      args:
        chdir: /tmp
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout

    - name: Set up cron job to check server uptime
      cron:
        name: check_server_uptime
        minute: 0
        hour: 0
        job: /usr/bin/uptime >> /var/log/server_uptime.log 2>&1
        state: present
