---
- name: Execute bash script and set up cron job
  hosts: all
  become: true

  tasks:
    - name: Transfer bash script to slave node
      copy:
        src: /home/vagrant/LAMP-Stack/lamp-deploy.sh
        dest: /home/vagrant/lamp-deploy.sh
        owner: root
        group: root
        mode: 0755

    - name: Execute the bash script
      shell: /home/vagrant/lamp-deploy.sh

    
    - name: Set up cron job to check server uptime
      cron:
        name: check_server_uptime
        minute: 0
        hour: 0
        job: /usr/bin/uptime >> /var/log/server_uptime.log 2>&1
        state: present
